apiVersion: batch/v1
kind: Job
metadata:
  name: paddle-cluster-job-gpu
spec:
  parallelism: 3
  template:
    metadata:
      name: paddle-cluster-job-gpu
    spec:
      volumes:
      - name: glusterfsvol
        glusterfs:
          endpoints: glusterfs-cluster
          path: gfs_vol
      - name: cuda-libs
        hostPath:
          path: /usr/local/nvidia/lib64/
      containers:
      - name: trainer
        image: yancey1989/paddle_k8s_quickstart_gpu
        imagePullPolicy: Always
        command: ["/bin/bash", "/root/start.sh"]
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 5Gi
            alpha.kubernetes.io/nvidia-gpu: 2
        env:
        - name: TRAINER_COUNT
          value: "3"
        - name: JOB_NAME
          value: paddle-cluster-job-gpu
        - name: JOB_PATH
          value: /mnt/glusterfs/yanxu05
        # using downward API to reference pod namespace
        - name: JOB_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TRAINER_PACKAGE
          value: /root/quick_start
        - name: CONF_PADDLE_NIC
          value: eth0
        - name: CONF_PADDLE_PORT
          value: "7164"
        - name: CONF_PADDLE_PORTS_NUM
          value: "2"
        - name: CONF_PADDLE_PORTS_NUM_SPARSE
          value: "2"
        - name: CONF_PADDLE_GRADIENT_NUM
          value: "3"
        - name: TRAINER_COUNT
          value: "3"
        - name: TRAINER_THREAD
          value: "2"
        - name: LD_LIBRARY_PATH
          value: "/usr/lib64:/usr/local/lib:/usr/local/lib64:/usr/local/nvidia/lib64"
        - name: USE_GPU
          value: "1"
        volumeMounts:
        - mountPath: /mnt/glusterfs
          name: glusterfsvol
        - mountPath: "/usr/local/nvidia/lib64"
          name: cuda-libs
        ports:
        - name: jobport0
          containerPort: 7164
        - name: jobport1
          containerPort: 7165
        - name: jobport2
          containerPort: 7166
        - name: jobport3
          containerPort: 7167
      restartPolicy: Never
