apiVersion: batch/v1
kind: Job
metadata:
  name: paddle-cluster-job
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      name: paddle-cluster-job
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      - name: cuda-libs
        hostPath:
          path: /home/wuyi/myhostpath/lib64
      containers:
      - name: trainer
#        image: paddledev/paddle-tutorial:k8s_train
        image: docker.paddlepaddle.org/paddle_dist_train:0.9.0-gpu
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command: ["/bin/bash", "/root/start.sh"]
        #command: ["sleep", "3600"]
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 5Gi
            alpha.kubernetes.io/nvidia-gpu: 2
        env:
        - name: SPLIT_COUNT
          value: "3"
        - name: JOB_NAME
          value: paddle-cluster-job
        - name: JOB_PATH
          value: /home/jobpath
        # using downward API to reference pod namespace
        - name: JOB_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TRAIN_CONFIG_DIR
          value: quick_start
        - name: CONF_PADDLE_NIC
          value: eth0
        - name: CONF_PADDLE_PORT
          value: "7164"
        - name: CONF_PADDLE_PORTS_NUM
          value: "2"
        - name: CONF_PADDLE_PORTS_NUM_SPARSE
          value: "2"
        - name: CONF_PADDLE_GRADIENT_NUM
          value: "3"
        - name: TRAINER_COUNT
          value: "3"
        - name: LD_LIBRARY_PATH
          value: "/usr/lib64:/usr/local/lib:/usr/local/lib64"
        volumeMounts:
        - mountPath: "/home/jobpath"
          name: nfs
        - mountPath: "/usr/lib64"
          name: cuda-libs
        ports:
        - name: jobport0
          hostPort: 7164
          containerPort: 7164
        - name: jobport1
          hostPort: 7165
          containerPort: 7165
        - name: jobport2
          hostPort: 7166
          containerPort: 7166
        - name: jobport3
          hostPort: 7167
          containerPort: 7167
      restartPolicy: Never
