apiVersion: batch/v1
kind: Job
metadata:
  name: paddle-cluster-job
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      name: paddle-cluster-job
    spec:
      volumes:
      - name: glusterfsvol
        glusterfs:
          endpoints: glusterfs-cluster
          path: gfs_vol
      containers:
      - name: trainer
        image: yancey1989/paddle_k8s_quickstart
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command: ["/bin/bash", "/root/start.sh"]
        #command: ["sleep", "3600"]
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 5Gi
        env:
        - name: SPLIT_COUNT
          value: "3"
        - name: JOB_NAME
          value: paddle-cluster-job
        - name: JOB_PATH
          value: /mnt/glusterfs/yanxu05/
        - name: PYTHONHOME
          value: /usr/local
        # using downward API to reference pod namespace
        - name: JOB_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TRAINER_PACKAGE
          value: /root/quick_start
        - name: CONF_PADDLE_NIC
          value: eth0
        - name: CONF_PADDLE_PORT
          value: "7164"
        - name: CONF_PADDLE_PORTS_NUM
          value: "2"
        - name: CONF_PADDLE_PORTS_NUM_SPARSE
          value: "2"
        - name: CONF_PADDLE_GRADIENT_NUM
          value: "3"
        - name: TRAINER_COUNT
          value: "3"
        volumeMounts:
        - mountPath: /mnt/glusterfs
          name: glusterfsvol
        ports:
        - name: jobport0
          hostPort: 7164
          containerPort: 7164
        - name: jobport1
          hostPort: 7165
          containerPort: 7165
        - name: jobport2
          hostPort: 7166
          containerPort: 7166
        - name: jobport3
          hostPort: 7167
          containerPort: 7167
      restartPolicy: Never
