apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 172.24.2.32
status:
  loadBalancer:
    ingress:
      - ip: 172.24.2.32
